apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    name: adi-node
  ports:
    - name: node-server
      protocol: TCP
      port: 8080
      targetPort: 8080
